spring.application.name=E-CommerceSpring
<<<<<<< HEAD:src/main/resources/application.properties
server.port=${PORT:8080}
=======
server.port=${PORT:5454}
>>>>>>> bd967d6 (added):E-CommerceSpring/src/main/resources/application.properties

# mysql database configuration
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerceSpring}
spring.datasource.username=root
<<<<<<< HEAD:src/main/resources/application.properties
spring.datasource.password=${DB_PASSWORD:_VarRkshv@123}
=======
    spring.datasource.password=${DB_PASSWORD:_VarRkshv@123}
>>>>>>> bd967d6 (added):E-CommerceSpring/src/main/resources/application.properties
spring.jpa.hibernate.ddl-auto=update
stripe.secretKey = sk_test_51SAXfSLvlliK4x7jFoTGIOc2uVuk1IFMKJeabQpaoD2p0IZjMrP164quntbuJ4pxgYxlDwiGkcZpzsPhxjZ6m07e00skiCENTA